---
- name: Create a user 
  hosts: Testing_CA.oci.com
  become: yes
  tasks:
  - name: Add user magzoub
    user:
      name: magzoub
      shell: /bin/sh
      home: /home/magzoub
      state: present
      become: yes
      become_method: su
      
  - name: Add user fatima
    user:
      name: fatima
      shell: /bin/sh
      home: /home/fatima
      state: present
      become: yes
      become_method: su
