---
- name: Create a user 
  hosts: Testing_CA.oci.com
  tasks:
  - name: Add user magzoub
    user:
      name: magzoub
      shell: /bin/bash
      home: /home/magzoub
  - name: Add user fatima
    user:
      name: fatima
      shell: /bin/bash
      home: /home/fatima
